<a href="https://colab.research.google.com/github/shivaprasannatejadharma-arch/ML_LAB_2026-27/blob/main/pandasexcel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd

In [7]:
df2=pd.read_excel("/content/Product-Sales-Region.xlsx")

In [8]:
df2

,Date,Region,Product,Quantity,UnitPrice,StoreLocation,CustomerType,Discount,Salesperson,TotalPrice,PaymentMethod,Promotion,Returned,OrderID,CustomerName,ShippingCost,OrderDate,DeliveryDate,RegionManager
0,2023-02-23,East,Laptop,14,163.60,Store B,Wholesale,0.00,Eva,2290.400,Online,FREESHIP,0,REG100000,Cust 6583,43.34,2023-02-23,2023-02-27,Eric
1,2024-12-19,South,Phone,1,544.01,Store A,Retail,0.00,Alice,544.010,Gift Card,SAVE10,0,REG100001,Cust 2144,5.30,2024-12-19,2024-12-28,Sophie
2,2023-05-10,North,Desk,14,346.18,Store B,Wholesale,0.10,Alice,4361.868,Online,WINTER15,0,REG100002,Cust 5998,20.46,2023-05-10,2023-05-19,Ryan
3,2025-02-26,Central,Chair,18,384.82,Store A,Wholesale,0.15,Frank,5887.746,Gift Card,FREESHIP,0,REG100003,Cust 7136,27.95,2025-02-26,2025-03-02,Cameron
4,2023-06-24,East,Desk,18,237.76,Store C,Retail,0.00,Carlos,4279.680,Online,SAVE10,0,REG100004,Cust 6506,5.73,2023-06-24,2023-06-27,Eric
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,2025-02-17,West,Desk,13,134.56,Store D,Retail,0.05,Carlos,1661.816,Credit Card,WINTER15,0,REG101495,Cust 5227,35.63,2025-02-17,2025-02-22,Wendy
1496,2024-01-11,South,Chair,18,209.75,Store C,Wholesale,0.15,Frank,3209.175,Debit Card,FREESHIP,0,REG101496,Cust 5559,45.93,2024-01-11,2024-01-17,Sophie
1497,2024-07-27,East,Desk,1,272.50,Store A,Wholesale,0.00,Eva,272.500,Gift Card,WINTER15,0,REG101497,Cust 8981,35.56,2024-07-27,2024-08-03,Eric
1498,2024-12-03,Central,Monitor,14,262.67,Store A,Retail,0.05,Carlos,3493.511,Gift Card,SAVE10,0,REG101498,Cust 1824,24.53,2024-12-03,2024-12-10,Cameron
1499,2025-05-09,West,Chair,13,221.39,Store D,Wholesale,0.00,Frank,2878.070,Debit Card,FREESHIP,1,REG101499,Cust 1935,21.05,2025-05-09,2025-05-13,Wendy

In [10]:
df2.describe()

,Date,Quantity,UnitPrice,Discount,TotalPrice,Returned,ShippingCost,OrderDate,DeliveryDate
count,1500,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500,1500
mean,2024-04-07 21:35:02.400000256,10.410667,298.826947,0.073133,2919.994952,0.248000,27.507293,2024-04-07 21:35:02.400000256,2024-04-13 22:36:28.799999744
min,2023-01-01 00:00:00,1.000000,5.520000,0.000000,6.970000,0.000000,5.010000,2023-01-01 00:00:00,2023-01-08 00:00:00
25%,2023-08-20 00:00:00,5.000000,151.020000,0.000000,867.136250,0.000000,16.700000,2023-08-20 00:00:00,2023-08-25 12:00:00
50%,2024-04-08 12:00:00,11.000000,294.740000,0.050000,2174.724000,0.000000,27.100000,2024-04-08 12:00:00,2024-04-15 12:00:00
75%,2024-12-07 06:00:00,15.000000,446.702500,0.100000,4414.723500,0.000000,38.635000,2024-12-07 06:00:00,2024-12-13 06:00:00
max,2025-06-30 00:00:00,20.000000,599.720000,0.150000,11077.000000,1.000000,49.980000,2025-06-30 00:00:00,2025-07-10 00:00:00
std,NaN,5.735732,169.100075,0.055979,2522.789977,0.431996,13.093453,NaN,NaN

In [17]:
df2.Date

0      2023-02-23
1      2024-12-19
2      2023-05-10
3      2025-02-26
4      2023-06-24
          ...
1495   2025-02-17
1496   2024-01-11
1497   2024-07-27
1498   2024-12-03
1499   2025-05-09
Name: Date, Length: 1500, dtype: datetime64[ns]

In [18]:
df2.head()

,Date,Region,Product,Quantity,UnitPrice,StoreLocation,CustomerType,Discount,Salesperson,TotalPrice,PaymentMethod,Promotion,Returned,OrderID,CustomerName,ShippingCost,OrderDate,DeliveryDate,RegionManager
0,2023-02-23,East,Laptop,14,163.60,Store B,Wholesale,0.00,Eva,2290.400,Online,FREESHIP,0,REG100000,Cust 6583,43.34,2023-02-23,2023-02-27,Eric
1,2024-12-19,South,Phone,1,544.01,Store A,Retail,0.00,Alice,544.010,Gift Card,SAVE10,0,REG100001,Cust 2144,5.30,2024-12-19,2024-12-28,Sophie
2,2023-05-10,North,Desk,14,346.18,Store B,Wholesale,0.10,Alice,4361.868,Online,WINTER15,0,REG100002,Cust 5998,20.46,2023-05-10,2023-05-19,Ryan
3,2025-02-26,Central,Chair,18,384.82,Store A,Wholesale,0.15,Frank,5887.746,Gift Card,FREESHIP,0,REG100003,Cust 7136,27.95,2025-02-26,2025-03-02,Cameron
4,2023-06-24,East,Desk,18,237.76,Store C,Retail,0.00,Carlos,4279.680,Online,SAVE10,0,REG100004,Cust 6506,5.73,2023-06-24,2023-06-27,Eric

In [19]:
df2.tail()

,Date,Region,Product,Quantity,UnitPrice,StoreLocation,CustomerType,Discount,Salesperson,TotalPrice,PaymentMethod,Promotion,Returned,OrderID,CustomerName,ShippingCost,OrderDate,DeliveryDate,RegionManager
1495,2025-02-17,West,Desk,13,134.56,Store D,Retail,0.05,Carlos,1661.816,Credit Card,WINTER15,0,REG101495,Cust 5227,35.63,2025-02-17,2025-02-22,Wendy
1496,2024-01-11,South,Chair,18,209.75,Store C,Wholesale,0.15,Frank,3209.175,Debit Card,FREESHIP,0,REG101496,Cust 5559,45.93,2024-01-11,2024-01-17,Sophie
1497,2024-07-27,East,Desk,1,272.50,Store A,Wholesale,0.00,Eva,272.500,Gift Card,WINTER15,0,REG101497,Cust 8981,35.56,2024-07-27,2024-08-03,Eric
1498,2024-12-03,Central,Monitor,14,262.67,Store A,Retail,0.05,Carlos,3493.511,Gift Card,SAVE10,0,REG101498,Cust 1824,24.53,2024-12-03,2024-12-10,Cameron
1499,2025-05-09,West,Chair,13,221.39,Store D,Wholesale,0.00,Frank,2878.070,Debit Card,FREESHIP,1,REG101499,Cust 1935,21.05,2025-05-09,2025-05-13,Wendy

In [20]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           1500 non-null   datetime64[ns]
 1   Region         1500 non-null   object
 2   Product        1500 non-null   object
 3   Quantity       1500 non-null   int64
 4   UnitPrice      1500 non-null   float64
 5   StoreLocation  1500 non-null   object
 6   CustomerType   1500 non-null   object
 7   Discount       1500 non-null   float64
 8   Salesperson    1500 non-null   object
 9   TotalPrice     1500 non-null   float64
 10  PaymentMethod  1500 non-null   object
 11  Promotion      1130 non-null   object
 12  Returned       1500 non-null   int64
 13  OrderID        1500 non-null   object
 14  CustomerName   1500 non-null   object
 15  ShippingCost   1500 non-null   float64
 16  OrderDate      1500 non-null   datetime64[ns]
 17  DeliveryDate   1500 non-null   datetime64[ns]
 18  RegionManager  1500 non-null   object
dtypes: datetime64[ns](3), float64(4), int64(2), object(10)
memory usage: 222.8+ KB